### ISSUE TITLE
No fort to walk to! (Map scanning down)

### ISSUE THREAD

**Issue by BoBeR182** [BoBeR182/PoGoBoWo#62] opened 2016-08-03 20:39 UTC
## Expected Behavior

Find next fort.

## Actual Behavior

No fort to walk to!

### Environmental Information

Operating System: Linux
Commit: 5e001f978a791bb484f188cb54f68a4401bcc8c6
config.json: NA

## Steps to reproduce

1. Run Bot
2. Login
3. Endlessly wait for a fort.

**Comment by BoBeR182** [comment] 2016-08-03 20:40
Other Bots are reporting the same problem, seems like Niantic may have patched something with the map scanning code.

**Comment by Kaashond** [comment] 2016-08-03 21:11
Same problem here
It ends with this error

CTraceback (most recent call last):
  File "pokebot.py", line 109, in <module>
    main()
  File "pokebot.py", line 99, in main
    api.main_loop()
  File "/home/pgoapi.py", line 644, in main_loop
    self.spin_near_fort()  # check local pokestop
  File "/home/pgoapi.py", line 307, in spin_near_fort
    sleep(3 * random.random() + 5)
KeyboardInterrupt

**Comment by BoBeR182** [comment] 2016-08-03 21:12
@Kaashond That is not an error, that is you forcing the bot to close.

**Comment by VeNoMouS** [comment] 2016-08-03 22:02
@BoBeR182 yea its happened in the past ~5hrs...

**Comment by BoBeR182** [comment] 2016-08-03 22:09
Currently I am waiting for the following upstream API fix. https://github.com/AeonLucid/POGOProtos/issues/131

**Comment by VeNoMouS** [comment] 2016-08-03 22:10
@BoBeR182 i was following pokego++ etc for iphone jailbreaks, they all reporting same issue... https://www.reddit.com/r/jailbreak/comments/4w0uiz/request_bypass_new_pok%C3%A9mon_go_version_requirement/

**Comment by etrevis** [comment] 2016-08-04 06:55
Check this reddit https://m.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/?sort=confidence&utm_source=mweb_redirect&compact=true

**Comment by BoBeR182** [comment] 2016-08-05 17:03
https://www.reddit.com/live/xdkgkncepvcq/

**Comment by VeNoMouS** [comment] 2016-08-07 00:16
@BoBeR182 its now fixed https://github.com/keyphact/pgoapi

**Comment by BoBeR182** [comment] 2016-08-07 00:18
Time to merge changes, I'll get to work on it. Anyone makes a pull request first ill be happy to merge.

**Comment by VeNoMouS** [comment] 2016-08-07 00:19
It's a direct drop in replacement , running into a few issues in your code, stepping through it atm..

**Comment by BoBeR182** [comment] 2016-08-07 00:23
Ill make a new branch we can start merging and work at it.

**Comment by VeNoMouS** [comment] 2016-08-07 00:53
@BoBeR182 , get on discord , in general and add me

**Comment by etrevis** [comment] 2016-08-07 15:10
I suggest to divide the pgoapi part from the actual bot, or probably at every update we have to work a lot

**Comment by VeNoMouS** [comment] 2016-08-07 22:08
@etrevis yea, i had discussed this with @BoBeR182  yesterday and i had already started this, this way its a direct drop in replacement should the api change again.

**Comment by BoBeR182** [comment] 2016-08-07 23:58
Nice, hopefully this bot will be able to recover faster in the future.

**Comment by VeNoMouS** [comment] 2016-08-08 06:20
Well... my dev branch appears to be going.... I had some down time today at work, so i took etevis changes and split it all out and cleaned it, ALOT of cleanup still needs to be done, but at this stage its working..

**Comment by VeNoMouS** [comment] 2016-08-08 06:42
Ok, some quick haxing and brought web interface online.

**Comment by VeNoMouS** [comment] 2016-08-08 06:59
One bug I think is happening, is it appears to not be hitting the poke stops, so will need to look into why... may be related to map objects unsure.... i'm going home ...

**Comment by VeNoMouS** [comment] 2016-08-08 07:02
Ok... i quickly checked where spin_near_fort() was being called... REALLY going to fix that... also

```
        for pokemon_distance in pokemon_distances:
            target = pokemon_distance
            self.log.debug("Catching pokemon: : %s, distance: %f meters", target[0], target[1])
            self.log.info("Catching Pokemon: %s", self.pokemon_names[str(target[0]['pokemon_id'])])
            return self.encounter_pokemon(target[0])
            if sum(self.pokeballs) == 0:
                self.spin_near_fort()
```

LOL at that if statement after the return..

**Comment by VeNoMouS** [comment] 2016-08-08 09:59
Ok, i found the fort spin issue... I'll issue a fix after some other clean up..

**Comment by neohunter** [comment] 2016-08-08 11:56
@VeNoMouS Where are you working on? on your fork/new-api-update?

**Comment by VeNoMouS** [comment] 2016-08-08 11:57
yea, I haven't updated in a few hours , been working on improving some of your fort code etc...

**Comment by etrevis** [comment] 2016-08-08 16:13
@VeNoMouS Please next time before you leave make a commit, now i'm probably working on the same things you done few hours ago ;)

**Comment by VeNoMouS** [comment] 2016-08-08 21:54
@etrevis I assume you mean a PR not a commit, The code I've written is a bit of a mess atm but it works.

I was going to clean up the code before I issues a PR

As it is, I have discovered a number of logic bugs with the original code and.... if you haven't noticed, there is a bug with the fort spin atm, returning a code 2 which is out of range, even if your 0.00 meters from it, though sometimes it does return a code of 1 with items.

I'm not sure if its a time bug between issuing last request etc... more investigation is required.

**Comment by etrevis** [comment] 2016-08-09 21:43
@VeNoMouS I was thinking about a PR
Anyway in my [latest one](https://github.com/etrevis/PoGo-Bot/commit/7cf6f6d419333c6e50e7132109ed346bd5ba2045) i fixed almost everything (except the web module), give it a look. Also updated to the latest pgoapi, we should do that more frequently.

There was two main problems blocking the fort spinnig:

- the `spin_near_fort` method was calling `walk_to` before the `fort_search` api request, and `walk_to` also was calling `spin_near_fort` before arriving at the fort. So basically nothing was happening.

- new pgoapi also need elevation data, i've implemented it in a 'dirty' way (using another gmaps module, the official one) because of the previous really dirty code


TODO:

- unification to googlemaps package instead of gmaps (which has almost no documentation, and is  probably outdated)

- storing `GET_MAP_OBJECTS` response (maybe if in a .json file). I think it's better if done by the new method `response_parser()`.

- some more cleanig and organization (right now this bot will be idenfied by AI with machine leaning in few minutes)

**Comment by bertjan** [comment] 2016-08-10 06:20
@etrevis i've tested [your latest commit](https://github.com/etrevis/PoGo-Bot/commit/7cf6f6d419333c6e50e7132109ed346bd5ba2045).
It seems to run well, just wanted to share a few things I ran into when trying it out:
- The reference to the encryption lib is hard-coded to encrypt.dll: `OSError: pgoapi/encrypt.dll: invalid ELF header`. I'm running the bot on Linux so I needed to change that to libencrypt.so. It would be nice if this was configurable, or, even better, the host os is auto detected.
- The bot had some catching up to do on the inventory; this made me get throttled a few times: `pgoapi.exceptions.ServerSideRequestThrottlingException: Request throttled by server... slow down man`. After starting the bot a few times, the backlog was gone and it kept running.
- The bot now exists on the throttling error above. I think it would be better to just have it pause and retry there. 
- It seems that  GMAPS_API_KEY is now back to a string value (it was an array before); the googlemaps package complained about an invalid API key (probably because it was fed an array instead of a single value)
- The Google maps Elevation API needs to be enabled now `ApiError: REQUEST_DENIED (This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/elevation_backend?project=_)`

**Comment by VeNoMouS** [comment] 2016-08-10 06:59
```
def get_encryption_lib_path():
    lib_path = ""
    # win32 doesn't mean necessarily 32 bits
    if sys.platform == "win32":
        if platform.architecture()[0] == '64bit':
            lib_path = os.path.join(os.path.dirname(__file__), "../libs/libencrypt-windows-64.dll")
        else:
            lib_path = os.path.join(os.path.dirname(__file__), "../libs/libencrypt-windows-32.dll")

    elif sys.platform == "darwin":
        lib_path = os.path.join(os.path.dirname(__file__), "../libs/libencrypt-osx-64.so")

    elif os.uname()[4].startswith("arm") and platform.architecture()[0] == '32bit':
        lib_path = os.path.join(os.path.dirname(__file__), "../libs/libencrypt-linux-arm-32.so")

    elif sys.platform.startswith('linux'):
        if platform.architecture()[0] == '64bit':
            lib_path = os.path.join(os.path.dirname(__file__), "../libs/libencrypt-linux-x86-64.so")
        else:
            lib_path = os.path.join(os.path.dirname(__file__), "../libs/libencrypt-linux-x86-32.so")

    else:
        err = "Unexpected/unsupported platform '{}'".format(sys.platform)
        log.error(err)
        raise Exception(err)

    if not os.path.isfile(lib_path):
        err = "Could not find {} encryption library {}".format(sys.platform, lib_path)
        log.error(err)
        raise Exception(err)

    return lib_path
```

just saying... :P

**Comment by VeNoMouS** [comment] 2016-08-10 07:04
@etrevis , I haven't had further time to work on this... maybe this can help you out a little with the fort stuff...

```
def fort_details(self, fort_id, latitude, longitude):
        if fort_id not in self._fort_details_cache:
            try:
                self._fort_details_cache[fort_id] = self.pgoapi_request.fort_details(fort_id=fort_id, latitude=latitude, longitude=longitude).call()['responses']['FORT_DETAILS']
            except:
                self.log.info("Fort Lookup Failed...")
                pass
        sleep(2)
        return self._fort_details_cache.get(fort_id,{})
                
    ##################################################################################################
    
    def fortInRange(self):
        for fort in self._forts:
            if distance_in_meters(self._posf, (fort.get('latitude'), fort.get('longitude')) ) <= 30:
                details = self.fort_details(fort.get('id'), fort.get('latitude'), fort.get('longitude'))
                if fort.get('id') in self._visted_forts:
                    self.log.info("fortInRange() found (" + details.get('name') + ") " + fort.get('id') + ", now = " + str(int(time())) + ", stored = " + str(self._visted_forts[fort['id']]))
                    if (self._visted_forts[fort.get('id')] + 300) > int(time()):
                        self.log.info("fortInRange() Skipping fort location due to time limit...")
                        continue
                
                sleep(10)
                #self.walk_to((fort['latitude'], fort['longitude']))
                res = self.pgoapi_request.fort_search(fort_id=fort['id'], fort_latitude=fort['latitude'], fort_longitude=fort['longitude'], player_latitude=f2i(self._posf[0]), player_longitude=f2i(self._posf[1])).call()['responses']['FORT_SEARCH']
                if res.get('result') == 2:
                    self.log.info("fortInRange() fort out of range.. " + str(distance_in_meters(self._posf, (fort.get('latitude'), fort.get('longitude')) )))
                if res.get('result') == 1:
                    items_awarded = res.get('items_awarded', {})
                    pprint(items_awarded)
                    #if items_awarded:
                print ""
                self._visted_forts[fort.get('id')] = int(time())
                self.log.info("fortInRange() Fort (%s) spinned: %s", fort.get('id'), res)
```

etc... just some of the stuff I was working on.

**Comment by etrevis** [comment] 2016-08-10 08:38
@bertjan yes encryption path was hardcoded, now i've just inserted @VeNoMouS's code (thanks a lot!). 

- Regarding throttling, i've also catched that, the cause (in my case) was the too quick realeasing algorithm, fixed. 
- I completely removed the gmaps keys list (or array), in the config you should put one single api key activated also for elevation request. I think it was an unnecessary complication.
- @VeNoMouS i'don't any see problem in your code, but only readed it quickly. where have you found `response['result']` informations/description?
- i'll send a new commit in few minutes, then i'll start working on catching `ServerSideRequestThrottlingException` excep in main loop

**Comment by VeNoMouS** [comment] 2016-08-10 08:40
1 = you got items, and you can element items_awarded, 2 too far away , -1 i think is softban.

**Comment by etrevis** [comment] 2016-08-10 08:46
I asked beacause sometimes i got 3 lol

**Closed** 2016-08-11 05:25 UTC
Labels: bug, help wanted

**Comment by begpl** [comment] 2016-08-11 07:26
Now with "USE_GOOGLE": false it uses google:
```
[ERROR] Main loop has an ERROR, restarting {u'routes': [], u'status': u'REQUEST_DENIED', u'error_message': u'The provided API key is invalid.', 'url': u'https://maps.googleapis.com/maps/api/directions/json?origin=&destination=&waypoints=&mode=walking&key=INSERT_API_KEY_OR_KEYS_HERE&units=metric&sensor=false'}
Traceback (most recent call last):
  File "run_bot.py", line 122, in main
    bot.main_loop()
  File "/home/PoGoBoWo/pogobot/pogobot.py", line 645, in main_loop
    self.heartbeat()
  File "/home/PoGoBoWo/pogobot/pogobot.py", line 217, in heartbeat
    self.spin_near_fort()
  File "/home/PoGoBoWo/pogobot/pogobot.py", line 279, in spin_near_fort
    self.walk_to((fort['latitude'], fort['longitude']))
  File "/home/PoGoBoWo/pogobot/pogobot.py", line 223, in walk_to
    steps = get_route(self._posf, loc, self.GMAPS_KEY)
  File "/home/PoGoBoWo/pogobot/location.py", line 28, in get_route
    d = directions_service.directions(origin, destination, mode="walking", units="metric")
  File "/usr/local/lib/python2.7/dist-packages/gmaps/directions.py", line 62, in directions
    return self._make_request(self.DIRECTIONS_URL, parameters, "routes")
  File "/usr/local/lib/python2.7/dist-packages/gmaps/client.py", line 89, in _make_request
    )(response)
RequestDenied: {u'routes': [], u'status': u'REQUEST_DENIED', u'error_message': u'The provided API key is invalid.', 'url': u'https://maps.googleapis.com/maps/api/directions/json?origi
```

**Comment by etrevis** [comment] 2016-08-11 14:25
@begpl yeah sorry I removed that option, now the bot will automatically uses google directions, you should activate the API key also for that (and elevation API)

**Comment by lukecbennett** [comment] 2016-08-11 16:53
guys am I missing something?

still getting the not fort error..

2016-08-11 17:53:03,324 [    pgoapi] [ INFO] Login process completed
2016-08-11 17:53:04,735 [    pgoapi] [ INFO] Less than 1 Poke Balls: Entering pokestops only
2016-08-11 17:53:12,724 [    pgoapi] [ERROR] No fort to walk to!
2016-08-11 17:53:14,712 [    pgoapi] [ INFO] Less than 1 Poke Balls: Entering pokestops only

**Comment by BoBeR182** [comment] 2016-08-11 17:39
That happens until the first full heartbeat sometimes, let it run a bit longer and create a new issue if it persists.

**Comment by lukecbennett** [comment] 2016-08-11 19:01
Ran it for 35mins without no luck. Any ideas?

**Comment by etrevis** [comment] 2016-08-11 19:47
@lukecbennett actually you have to use the [new-api branch](https://github.com/BoBeR182/PoGoBoWo/tree/new-api-update), master branch is not really up to date

**Comment by terabyte12** [comment] 2016-08-11 20:35
I'm getting the following. 

`016-08-11 16:33:43,983 [   pogobot] [ INFO] Walking to fort at 42.748012,-73.758762
2016-08-11 16:33:44,134 [   run_bot] [ERROR] Main loop has an ERROR, restarting Invalid API key provided.
Traceback (most recent call last):
  File "run_bot.py", line 122, in main
    bot.main_loop()
  File "C:\PoGoBoWo\pogobot\pogobot.py", line 645, in main_loop
    self.heartbeat()
  File "C:\PoGoBoWo\pogobot\pogobot.py", line 217, in heartbeat
    self.spin_near_fort()
  File "C:\PoGoBoWo\pogobot\pogobot.py", line 279, in spin_near_fort
    self.walk_to((fort['latitude'], fort['longitude']))
  File "C:\PoGoBoWo\pogobot\pogobot.py", line 226, in walk_to
    final_point = append_elevation(next_point[1][0], next_point[1][1], self.GMAPS_KEY)
  File "C:\PoGoBoWo\pogobot\location.py", line 47, in append_elevation
    request_google = Client(key=str(gmaps_api_key))
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 112, in __init__
    raise ValueError("Invalid API key provided.")
ValueError: Invalid API key provided.`

I've updated my API Key to have elevation as well.... I can see it hitting the directions API..

**Comment by lukecbennett** [comment] 2016-08-11 20:48
thanks a lot guys! good to be back on!

**Comment by terabyte12** [comment] 2016-08-11 20:48
I've fixed the issue. I was using an old config.json which must have been the problem.
